---
title: "Introduction to PET calculation"
author: "Yuxuan Xie"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
options(tibble.print_min = 5, tibble.print_max = 5)
```

## Load R package and data

```{r}
library(data.table)
library(magrittr)
```

```{r}
df_temp <- data.table(df_forcing) %>% 
  .[, .(date, Prcp, Ta, U2, ET = LE / 2.45)] %>% 
  .[, .(
    Prcp = sum(Prcp, na.rm=T),
    Ta = mean(Ta, na.rm=T),
    U2 = mean(U2, na.rm=T),
    ET = sum(ET, na.rm=T)
  ), .(year=year(date))] %>% 
  as.data.frame()
```

```{r}
ecm(df_temp, y_name = 'ET', x_name = c('Prcp', 'U2', 'Ta'))

df_temp2 <- data.frame(
  ET = c(NA, NA, 1, NA, 2, 5),
  Ta = c(NA, NA, 1, NA, 2, 5),
  U2 = c(NA, NA, 1, NA, 2, 5)
)

ecm(df_temp2, 'ET', c('Ta', 'U2'))
```

```{r}
df <- df_temp
y_name <- 'ET'
x_name <- c('Prcp', 'Ta', 'U2')
method = "feng2020"

plot(y, type = 'l')
plot(y_norm, type = 'l')
```

```{r}
i <- 3
plot(x[, i], type = 'l')
plot(x_norm[, i], type = 'l')

lm(y_norm ~ x_norm[, 1:2])
MASS::lm.ridge(y_norm ~ x_norm[, 1:2])

rtrend::mkTrend(y_norm)
```