```{r}
library(ggplot2)
library(data.table)
library(magrittr)
library(dplyr)
```

# visualization

```{r}
p <- df_forcing %>% 
  mutate(
    Rs_toa = hydroTools::cal_Rsi_toa(lat, yday(date)) %>% 
      hydroTools::MJ_2W(),
    ea = cal_es(Tdew)
  ) %>% 
  mutate(
    PET_PT1972 = PET_PT1972(Ta, Rn, Pa),
    PET_Penman1948 = PET_Penman1948(Ta, Rn, U2, VPD, Pa),
    PET_Yang2019 = PET_Yang2019(Rs, Rns, Rs_toa, Ts, lat, Pa),
    PET_Zhou2024 = PET_Zhou2024(Rn, Ta, Ts, ea, Pa)
  ) %>% 
  select(date, tidyselect::starts_with('PET'), -PET_ERA5L) %>% 
  melt(c('date')) %>% 
  .[between(year(date), 2018, 2020)] %>% 
  mutate(value = ifelse(value < 0, 0, value)) %>% 
  ggplot(aes(date, value)) +
  geom_point(size = 0.5) +
  facet_wrap(~variable, ncol = 1, scales = 'free')

ggsave(
  plot = p, filename = 'D:/Onedrive/Github/my_repos/hydroET/inst/Figures/Figure_PET_ts.jpg',
  dpi = 600, height = 5, width = 8
)
```

```{r}
system.time({
  df_forcing %>% 
  mutate(
    Rs_toa = hydroTools::cal_Rsi_toa(lat, yday(date)) %>% 
      hydroTools::MJ_2W(),
    ea = cal_es(Tdew)
  ) %>% 
  mutate(
    PET_PT1972 = PET_PT1972(Ta, Rn, Pa),
    PET_Penman1948 = PET_Penman1948(Ta, Rn, U2, VPD, Pa),
    PET_Yang2019 = PET_Yang2019(Rs, Rns, Rs_toa, Ts, lat, Pa),
    PET_Zhou2024 = PET_Zhou2024(Rn, Ta, Ts, ea, Pa)
  )
})

system.time({
  df_forcing %>% 
  mutate(
    Rs_toa = hydroTools::cal_Rsi_toa(lat, yday(date)) %>% 
      hydroTools::MJ_2W(),
    ea = cal_es(Tdew)
  ) %>% 
  mutate(
    PET_PT1972 = PET_PT1972(Ta, Rn, Pa),
    PET_Penman1948 = PET_Penman1948(Ta, Rn, U2, VPD, Pa),
    PET_Yang2019 = PET_Yang2019(Rs, Rns, Rs_toa, Ts, lat, Pa),
    PET_Zhou2024 = PET_Zhou2024_cpp(Rn, Ta, Ts, ea, Pa)
  )
})
```