# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

PET_PT1972 <- function(Ta, Rn, Pa) {
    .Call(`_hydroET_PET_PT1972`, Ta, Rn, Pa)
}

PET_Penman1948 <- function(Ta, Rn, U2, VPD, Pa) {
    .Call(`_hydroET_PET_Penman1948`, Ta, Rn, U2, VPD, Pa)
}

PET_Penman1948_max <- function(Ta, Tdry, Rn, U2, Pa) {
    .Call(`_hydroET_PET_Penman1948_max`, Ta, Tdry, Rn, U2, Pa)
}

PET_Yang2019 <- function(Rs, Rns, Rs_toa, Ts, lat, Pa) {
    .Call(`_hydroET_PET_Yang2019`, Rs, Rns, Rs_toa, Ts, lat, Pa)
}

PET_Zhou2024 <- function(Rn, Ta, Ts, ea, Pa, H, LE) {
    .Call(`_hydroET_PET_Zhou2024`, Rn, Ta, Ts, ea, Pa, H, LE)
}

cal_es <- function(Ta) {
    .Call(`_hydroET_cal_es`, Ta)
}

cal_lambda <- function(Ta) {
    .Call(`_hydroET_cal_lambda`, Ta)
}

cal_gma <- function(Ta, Pa) {
    .Call(`_hydroET_cal_gma`, Ta, Pa)
}

cal_delta <- function(Ta) {
    .Call(`_hydroET_cal_delta`, Ta)
}

cal_U2 <- function(Uz, z = 10.0) {
    .Call(`_hydroET_cal_U2`, Uz, z)
}

