# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cal_es <- function(Ta) {
    .Call(`_hydroET_cal_es`, Ta)
}

cal_lambda <- function(Ta) {
    .Call(`_hydroET_cal_lambda`, Ta)
}

cal_gma <- function(Ta, Pa) {
    .Call(`_hydroET_cal_gma`, Ta, Pa)
}

cal_delta <- function(Ta) {
    .Call(`_hydroET_cal_delta`, Ta)
}

cal_U2 <- function(Uz, z = 10.0) {
    .Call(`_hydroET_cal_U2`, Uz, z)
}

